### ISSUE TITLE
BBOX while configuring the job

### ISSUE THREAD

**Issue by mykolakozyr** [aspectumapp/up42-storage#13]
What's the purpose of the parameter `bbox` while job configuration?
It does not clip the image and returns the whole image even while not intersecting with it

**Comment by mykolakozyr** [comment]
The same question for the zoom level

**Comment by Kryvonis** [comment]
As I understand API require to return `bbox` and `zoom_level` from data block. For us, it's extra information but for further processing you should provide this parameters
