### ISSUE TITLE
USER input field in makefile

### ISSUE THREAD

**Issue by mykolakozyr** [aspectumapp/up42-storage#5]
Is this a required field and should be filled for every user?

https://github.com/aspectumapp/up42-storage/blob/d0122c951298ec4abae388c26a955ecaa5ea699d/Makefile#L2

**Comment by mykolakozyr** [comment]
The same question for the ID: the user defines it while building the block

**Comment by Kryvonis** [comment]
Only if you want to develop some modification. For update block into Docker registry. UID is the same
